CREATE INDEX VARIANT_RS_HASH ON Variant USING HASH(REF_SNP_ID);
CREATE INDEX VARIANT_METASEQ_HASH ON Variant USING HASH(METASEQ_ID);

CREATE INDEX VARIANT_IS_ADSP ON Variant(IS_ADSP_VARIANT) WHERE IS_ADSP_VARIANT IS TRUE;
CREATE INDEX VARIANT_BIN_INDEX ON Variant USING GIST(BIN_INDEX);

CREATE INDEX VARIANT_IDX01 ON Variant(CHROMOSOME, LOCATION_START, REF_SNP_ID, METASEQ_ID);



